# encoding: UTF-8

defaults: &defaults
  host: localhost
  port: 6379
  db: 0
  password:

development: &development
  <<: *defaults

test:
  <<: *development

production:
  <<: *development
  password: Fy958e5mmyb7Ta4H

